# 簡単なDockerイメージを作成してghcrにプッシュする
name: Build and Push to ghcr

# イベント
on:
  # メインブランチPUSH
  push:
    branches: [ "main" ]
  # 手動実行
  workflow_dispatch:

permissions:
  contents: read
  packages: write

# ジョブ
jobs:
  # Dockerビルドとghcrへのプッシュするジョブ
  build_and_push:

    # ランナー
    runs-on: ubuntu-latest

    # ステップ
    steps:
      # レポジトリからソースをチェックアウト
      - uses: actions/checkout@v3

      # Docker 環境セットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # ghcrへログイン
      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # GitHubのリポジトリの情報を変数にセット
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # 変数の中身をログに残す
      - name: show env.REPO
        run: echo ${{ env.REPO }}
        
      # Dockerビルドとghcrへのプッシュを実施
      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
